on:
  push: {}
  workflow_dispatch:
    inputs:
      key:
        required: true

jobs:
  add_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "abcdef" > ./README.md
      - uses: actions/cache/save@v4
        id: cache
        with:
          path: ./*
          key: custom-key
              
