on:
  push: {}
  workflow_dispatch: {}

jobs:
  add_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/save@v4
        id: cache
        with:
          path: ./README.md
          key: custom-key
              
