name: Test success() function behavior

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  A1:
    runs-on: ubuntu-latest
    steps:
      - name: Job A1 - Will succeed
        run: |
          sleep 30
          echo "Job A1 completed successfully"

  B1:
    runs-on: ubuntu-latest
    steps:
      - name: Job B1 - Will fail
        run: |
          echo "Job B1 will fail"
          exit 1

  A2:
    needs: A1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Checking specific job statuses:"
          echo "A1 status: ${{ needs.A1.result }}"
          echo "B1 status: ${{ needs.B1.result }}"

  A2-success:
    needs: A1
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Checking specific job statuses:"
          echo "A1 status: ${{ needs.A1.result }}"
          echo "B1 status: ${{ needs.B1.result }}"

  A2-failure:
    needs: A1
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Checking specific job statuses:"
          echo "A1 status: ${{ needs.A1.result }}"
          echo "B1 status: ${{ needs.B1.result }}"
